import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PostComposerProvider } from "@/components/post/post-composer-provider";
import { PushSetup } from "@/components/notifications/push-setup";
import { NotificationProvider } from "@/components/notifications/notification-provider";
import { ChatProvider } from "@/components/chat/chat-provider";
import { ChatPanel } from "@/components/chat/chat-panel";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostComposerProvider>
          <NotificationProvider>
            <ChatProvider>
              <PushSetup />
              {children}
              <ChatPanel />
            </ChatProvider>
          </NotificationProvider>
        </PostComposerProvider>
      </body>
    </html>
  );
}
